# Numero di accordi che si possono fare al pianoforte

In [17]:
# piramide numerica
import numpy as np
import gmpy2

ty = object  # IMPORTANT: allows mpz in NumPy arrays

def genera_piramide(n):
    # start with mpz(1)
    piramide = [
        np.array([gmpy2.mpz(1)], dtype=ty), # 1
        np.array([gmpy2.mpz(1), gmpy2.mpz(1)], dtype=ty)] # 1 1

    for i in range(1, n):
        prev = piramide[i]
        
        middle = [prev[j] + prev[j+1] for j in range(len(prev)-1)]
        
        row = np.array([gmpy2.mpz(1)] + middle + [gmpy2.mpz(1)],dtype=ty)

        piramide.append(row)
        
    return piramide


p = genera_piramide(88)

# print(p[-1])            # print piramide
print('Numero di accordi che si possono fare al pianoforte:',np.sum(p[-1])-1)     # print somma riga

Numero di accordi che si possono fare al pianoforte: 309485009821345068724781055


# piccolo teorema fermat


Sia $p$ primo e $a \in Z$ con $p$ che non divide $a$. Allora $a^{p-1} = 1mod p$

In [18]:
prime = np.array([x for x in range(1000) if gmpy2.is_prime(x)], dtype=ty)

for a in range(2,np.max(prime)*2):
    for p in prime:
        if type(a / p) == int:
            if a**(p-1) % p != 1:
                print(f"Fermat fallisce per a={a}, p={p}")
                break

print("Fermat tiene per tutti i casi testati")

Fermat tiene per tutti i casi testati


# tavole di composizione modulo N:

In [19]:
mod = 4

# tavole di composizione modulo N:

classes = np.array([i for i in range(mod)])
table_prod = np.outer(classes,classes.T) % mod
table_sum = np.array([[i+j for j in classes] for i in classes]) % mod
print(table_prod)
print(table_sum)

[[0 0 0 0]
 [0 1 2 3]
 [0 2 0 2]
 [0 3 2 1]]
[[0 1 2 3]
 [1 2 3 0]
 [2 3 0 1]
 [3 0 1 2]]


# Algoritmo euclideo

In [20]:
a = 107432895
b = 457445

r = {'i':a,'i+1':b}

while r['i+1'] != 0:
    r_next = r['i'] % r['i+1']
    r['i'] = r['i+1']
    r['i+1'] = r_next

print('MCD: ', r['i'])

MCD:  5


# IDENTITà di Bezout:

MCD(a,b) = au+bv

In [27]:
# obiettivo: trovare u,v t.c. MCD(a,b) = au + bv

a = gmpy2.mpz(110575433489)
b = gmpy2.mpz(4264)

r = {'i':a,'i+1':b}

quozienti = []
resti = [a,b]
dividendi = []
while r['i+1'] != 0:
    r_next = r['i'] % r['i+1']
    q = r['i'] // r['i+1']
    quozienti.append(q)
    resti.append(r_next)
    dividendi.append(r['i'])
    r['i'] = r['i+1']
    r['i+1'] = r_next

MCD = resti[-2]

# calcolo dei coefficienti:

n = len(quozienti) #dividendo7 = 2 e non è contenuto nell'array

xy = (dividendi[n-2],dividendi[n-1])
coeff = (1,-quozienti[n-2])

for i in range(n-3,-1,-1):
    print(f'{MCD}={coeff[0]}[{xy[0]}]{'+' if coeff[1]>0 else ''}{coeff[1]}[{xy[1]}]')
    coeff = (coeff[1],coeff[0]-quozienti[i]*coeff[1])
    xy = (dividendi[i],dividendi[i+1])
print(f'{MCD}={coeff[0]}[{xy[0]}]{'+' if coeff[1]>0 else ''}{coeff[1]}[{xy[1]}]')

if MCD != coeff[0]*xy[0] + coeff[1]*xy[1]:
    raise('Error in calculation')


1=1[41]-5[8]
1=-5[90]+11[41]
1=11[221]-27[90]
1=-27[311]+38[221]
1=38[3953]-483[311]
1=-483[4264]+521[3953]
1=521[110575433489]-13510741287[4264]
